# Generated by Django 5.1.3 on 2025-05-22 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sasuke', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='assigned_to',
            field=models.ManyToManyField(related_name='missions', to='sasuke.ninja'),
        ),
    ]
