# Generated by Django 5.2.1 on 2025-05-22 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sasuke', '0002_alter_mission_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ninja',
            name='jutsu',
            field=models.ManyToManyField(blank=True, related_name='ninjas', to='sasuke.jutsu'),
        ),
    ]
