# Generated by Django 5.2.1 on 2025-05-22 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sasuke', '0003_alter_ninja_jutsu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jutsu',
            name='chakra_cost',
        ),
    ]
