# Generated by Django 5.2.1 on 2025-05-22 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sasuke', '0004_remove_jutsu_chakra_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(related_name='teams', to='sasuke.ninja'),
        ),
    ]
